name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev xorg-dev

      - name: Install build dependencies
        run: |
          go install fyne.io/tools/cmd/fyne@latest

      - name: Build Linux
        run: make build-linux

      - name: Package Linux
        run: make package-linux

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-packages
          path: dist/*

  build-macos:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install build dependencies
        run: |
          go install fyne.io/tools/cmd/fyne@latest

      - name: Build macOS
        run: make build-darwin

      - name: Package macOS
        run: make package-darwin

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-packages
          path: dist/*

  release:
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-packages
          path: dist/

      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-packages
          path: dist/

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.deb
            dist/*.tar.xz
            dist/*.dmg
            dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}